name: C++ CI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      uses: actions/setup-cpp@v1
      with:
        compiler-version: '17'  

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest
